---
galaxy_info:
  author: Red Hat Consulting
  description: Role for Red Hat JBoss Enterprise Application Platform (EAP)
  company: Red Hat
  license: license (Apache)
  min_ansible_version: 2.3.1.0
  platforms:
   - name: EL
     versions:
     - 7
     - 6
  categories:
   - java
   - jboss
   - eap
dependencies:
