# <security-realm>
#   <authentication>
#   </authentication>
#   <authorization>
#   </authorization>
# </security-realm>
#
# <security-realms>
#   <security-realm name="ManagementRealm">
#     <authentication>
#       <local default-user="$local" skip-group-loading="true"/>
#       <properties path="mgmt-users.properties" relative-to="jboss.server.config.dir"/>
#     </authentication>
#     <authorization map-groups-to-roles="false">
#       <properties path="mgmt-groups.properties" relative-to="jboss.server.config.dir"/>
#     </authorization>
#   </security-realm>
#   <security-realm name="ApplicationRealm">
#     <authentication>
#       <local default-user="$local" allowed-users="*" skip-group-loading="true"/>
#       <properties path="application-users.properties" relative-to="jboss.server.config.dir"/>
#     </authentication>
#     <authorization>
#       <properties path="application-roles.properties" relative-to="jboss.server.config.dir"/>
#     </authorization>
#   </security-realm>
#   <security-realm name="HTTPSRealm">
#     <server-identities>
#       <ssl>
#         <keystore path="eapserver.jks" relative-to="jboss.server.config.dir" keystore-password="redhat1!" alias="httpsKeystore"/>
#       </ssl>
#     </server-identities>
#   </security-realm>
# </security-realms>

