---

- name: Copy server cert and key for {{ keystore.alias }}
  copy:
    src: "{{ item }}"
    dest: "{{ jboss_eap_config_dir }}/{{ item | basename }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    mode: u=rw,g=,o=
    remote_src: "{{ keystore.remote_src | default(False) | bool }}"
  with_items:
  - "{{ keystore.cert }}"
  - "{{ keystore.key }}"
  register: copy_cert_and_key

- when: copy_cert_and_key.changed
  block:
  - name: Create PKCS12 keystore for {{ keystore.alias }}
    become: true
    become_user: "{{ jboss_eap_user }}"
    command: >-
      openssl pkcs12 -export
      -in {{ keystore.cert | basename | quote }}
      -inkey {{ keystore.key | basename | quote }}
      -out {{ (keystore.alias ~ '.p12') | quote }}
      -name {{ keystore.alias | quote }}
      -passout {{ ('pass' ~ ':' ~ keystore.storepass ) | quote  }}
    args:
      chdir: "{{ jboss_eap_config_dir }}"
    #no_log: true

  - name: Remove keystore for {{ keystore.alias }}
    file:
      path: "{{ jboss_eap_config_dir }}/{{ keystore.file }}"
      state: absent
    register: remove_keystore

  - name: Create keystore for {{ keystore.alias }} from PKCS12 keystore
    become: true
    become_user: "{{ jboss_eap_user }}"
    command: >-
      keytool -importkeystore
      -alias {{ keystore.alias | quote }}
      -srckeystore {{ (keystore.alias ~ '.p12') | quote }}
      -srcstoretype PKCS12
      -srcstorepass {{ keystore.storepass | quote }}
      -destkeystore {{ keystore.file | quote }}
      -destkeypass {{ keystore.storepass | quote }}
      -deststorepass {{ keystore.storepass | quote }}
    args:
       chdir: "{{ jboss_eap_config_dir }}"
    #no_log: true

- name: File ownership and permissions on {{ keystore.alias }} keystore
  file:
    path: "{{ jboss_eap_config_dir }}/{{ keystore.file }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    mode: u=rw,g=,o=
