---
- name: Check if keystore exists
  stat:
    path: "{{ jboss_eap_config_dir }}/{{ keystore.file }}"
  register: check_keystore_exists

- name: Create jks keystore with self-signed certificate
  become: true
  become_user: "{{ jboss_eap_user }}"
  command: >-
    keytool
    -genkeypair
    -alias {{ keystore.alias | quote }}
    -keyalg RSA
    -keystore {{ keystore.file | quote }}
    -keypass {{ keystore.storepass | quote }}
    -storepass {{ keystore.storepass | quote }}
    -dname {{ keystore.dn_string | quote }}
    -validity 3650
  args:
     chdir: "{{ jboss_eap_config_dir }}"
  no_log: true
  when: >-
    keystore.dn_string is defined and
    not check_keystore_exists.stat.exists
  register: create_keystore

- name : Delete old entry for {{ keystore.alias }} from JBoss CLI truststore
  become: true
  become_user: "{{ jboss_eap_user }}"
  command: >-
    keytool -delete
    -alias {{ keystore.alias | quote }}
    -keystore ~/.jboss-cli.truststore
    -storepass cli_truststore
    -noprompt
  when: create_keystore.changed
  failed_when: false

- name: Import self-signed certificate into JBoss CLI truststore
  become: true
  become_user: "{{ jboss_eap_user }}"
  shell: >-
    keytool -exportcert
    -alias {{ keystore.alias | quote }}
    -keystore {{ keystore.file | quote }}
    -storepass {{ keystore.storepass | quote }}
    -rfc
    | keytool -importcert
    -alias {{ keystore.alias | quote }}
    -keystore ~/.jboss-cli.truststore
    -storepass cli_truststore
    -noprompt
  args:
     chdir: "{{ jboss_eap_config_dir }}"
  no_log: true
  when: create_keystore.changed
