---
- name: Copy JKS keystore for {{ keystore.alias }}
  copy:
    src: "{{ keystore.src }}"
    dest: "{{ jboss_eap_config_dir }}/{{ keystore.file }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    mode: u=rw,g=,o=
  register: create_keystore

- when: >-
    create_keystore.changed and
    keystore.jboss_cli_import is defined
  block:
  - name : Delete old entry for {{ keystore.jboss_cli_import }} from JBoss CLI truststore
    become: true
    become_user: "{{ jboss_eap_user }}"
    command: >-
      keytool -delete
      -alias {{ keystore.jboss_cli_import | quote }}
      -keystore ~/.jboss-cli.truststore
      -storepass cli_truststore
      -noprompt
    failed_when: false

  - name: Import {{ keystore.jboss_cli_import }} certificate into JBoss CLI truststore
    become: true
    become_user: "{{ jboss_eap_user }}"
    shell: >-
      keytool -exportcert
      -alias {{ keystore.jboss_cli_import | quote }}
      -keystore {{ keystore.file | quote }}
      -storepass {{ keystore.storepass | quote }}
      -rfc
      | keytool -importcert
      -alias {{ keystore.jboss_cli_import | quote }}
      -keystore ~/.jboss-cli.truststore
      -storepass cli_truststore
      -noprompt
    args:
       chdir: "{{ jboss_eap_config_dir }}"
    no_log: true
