---
# keystore.gencert is used for generating a self-signed certificate.
- include: create_keystore_gencert.yml
  when: keystore.gencert | default(False) | bool

# If keystore.cert is defined then copy cert and key to server and create
# keystore from these.
- include: create_keystore_from_x509.yml
  when: keystore.cert is defined

# keystore.src is for copying a precreated keystore containing the server
# cert and key.
- include: create_keystore_copy.yml
  when: keystore.src is defined
